MODULE soc_constants_mod

  IMPLICIT NONE
  
#ifdef SOC_SINGLE_PRECISION
  INTEGER, PARAMETER :: r_def=SELECTED_REAL_KIND(6, 37)
  INTEGER, PARAMETER :: i_def=SELECTED_INT_KIND(10)
#else
  INTEGER, PARAMETER :: r_def=SELECTED_REAL_KIND(15, 307)
  INTEGER, PARAMETER :: i_def=SELECTED_INT_KIND(10)
#endif

END MODULE soc_constants_mod
